# fly.toml app configuration file generated for pupusa-demo on 2024-03-22T22:32:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pupusa-demo'
primary_region = 'sjc'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512MB'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  destination = "/app/pb_data"
  source = "pb_data"
